import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const randonNumber = Math.floor(Math.random() * 2);

  // if (randonNumber === 1) {
  //   throw new Error('Error from RootLayout');
  // }

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
